name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # или выберите подходящий образ, совместимый с вашим Raspberry Pi
    steps:
    - name: Stop previous bot process
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no master@185.155.17.223 'pkill -f bot.py' || true

    - name: Update repository
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no master@185.155.17.223 'cd FlowergrammerBot && git pull'

    - name: Start new bot process
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        FLOWER_FOLDER_NAME: ${{ secrets.FLOWER_FOLDER_NAME }}
        FOLDER_URL: ${{ secrets.FOLDER_URL }}
      run: |
        ssh -o StrictHostKeyChecking=no master@185.155.17.223 "env SSH_PRIVATE_KEY='$SSH_PRIVATE_KEY' BOT_TOKEN='$BOT_TOKEN' ADMIN_IDS='$ADMIN_IDS' FLOWER_FOLDER_NAME='$FLOWER_FOLDER_NAME' FOLDER_URL='$FOLDER_URL' nohup /home/master/.pyenv/shims/python FlowergrammerBot/bot.py &"