name: Deploy to Raspberry Pi
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # или выберите подходящий образ, совместимый с вашим Raspberry Pi
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.RPI_IP_ADDRESS }}
            username: ${{ secrets.RPI_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.RPI_PORT }}
            script: |
              cd FlowergrammerBot
              echo "Stopping bot..."
              pkill -f bot.py;
              echo "Pulling latest code..."
              git pull
              echo "Sleeping for 3 seconds..."
              sleep 3
              echo "Starting bot..."
              nohup /home/master/.pyenv/shims/python bot.py &